#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Blog_MVC/Blog_MVC.csproj", "Blog_MVC/"]
COPY ["Blog_WebApi/Blog_WebApi.csproj", "Blog_WebApi/"]
COPY ["DAL/DAL.csproj", "DAL/"]
RUN dotnet restore "Blog_MVC/Blog_MVC.csproj"
COPY . .
WORKDIR "/src/Blog_MVC"
RUN dotnet build "Blog_MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Blog_MVC.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Blog_MVC.dll"]